variables:
  GIT_STRATEGY: none
stages:
  - test
test_job:
  stage: test
  only: 
    - master
  script:
    - cd /home
    - mkdir gitproject
    - cd gitproject
    - rm -rf /home/gitproject/gitrunner
    - git clone http://root:NpSam4AoyeQEWkW@8.217.35.128/root/gitrunner.git
    - cd ./gitrunner
    - dotnet build --configuration Release 
    - rm -rf /home/project/gitrunner
    - docker stop gitci
    - docker rm gitci
    - docker rmi gitciimages
    - dotnet publish -c Release --output /home/project/gitrunner
    - cd /home/project/gitrunner
    - docker build -t gitciimages .
    - docker run -d -v /home/project/gitrunner:/code -p 5001:80 --name gitci --restart always gitciimages
